-- This was generated by perplexity and isn't part of the course. It's to practice joins.


CREATE DATABASE IF NOT EXISTS relations_practice;
USE relations_practice;

CREATE TABLE cities (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(300) NOT NULL
);

CREATE TABLE addresses (
  id INT PRIMARY KEY AUTO_INCREMENT,
  street VARCHAR(300) NOT NULL,
  house_number VARCHAR(50) NOT NULL,
  city_id INT NOT NULL,
  CONSTRAINT fk_addresses_city
    FOREIGN KEY (city_id) REFERENCES cities(id)
);

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(300) NOT NULL,
  last_name VARCHAR(300) NOT NULL,
  email VARCHAR(300) NOT NULL,
  address_id INT NOT NULL,
  CONSTRAINT fk_users_address
    FOREIGN KEY (address_id) REFERENCES addresses(id)
);

-- INSERT INTO cities (name) VALUES
-- ('Berlin'),
-- ('New York'),
-- ('London'),
-- ('Paris');

-- INSERT INTO addresses (street, house_number, city_id) VALUES
-- ('Main Street', '1A', 1),     -- Berlin
-- ('Second Ave', '22', 2),      -- New York
-- ('Baker Street', '221B', 3),  -- London
-- ('River Road', '5', 4);       -- Paris

-- INSERT INTO users (first_name, last_name, email, address_id) VALUES
-- ('Max', 'Schwarz', 'max@test.com', 1),
-- ('Manuel', 'Lorenz', 'manu@test.com', 2),
-- ('Julie', 'Barnes', 'julie@barnes.com', 3),
-- ('Anna', 'Dubois', 'anna@dubois.fr', 4);


