-- CREATE TABLE time_blocks (
--   id INT PRIMARY KEY AUTO_INCREMENT,
--   title varchar(100) NOT NULL,
--   day_of_week ENUM(
--     'Monday',
--     'Tuesday',
--     'Wednesday',
--     'Thursday',
--     'Friday',
--     'Saturday',
--     'Sunday'
--   ) NOT NULL,
--   start_time TIME NOT NULL,
--   end_time TIME NOT NULL,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- INSERT INTO time_blocks(day_of_week, title, start_time, end_time)
-- VALUES('Sunday', 'Study Time', '01:30:00', '04:30:00');
-- INSERT INTO time_blocks(day_of_week, title, start_time, end_time)
-- VALUES('Monday', 'Work', '07:00:00', '03:30:00');
-- INSERT INTO time_blocks(day_of_week, title, start_time, end_time)
-- VALUES('Tuesday', 'Study', '01:00:00', '04:00:00');
-- INSERT INTO time_blocks(day_of_week, title, start_time, end_time)
-- VALUES('Wednesday', 'Work', '08:30:00', '05:00:00');
-- INSERT INTO time_blocks(day_of_week, title, start_time, end_time)
-- VALUES('Thursday', 'Study', '01:00:00', '04:00:00');
-- INSERT INTO time_blocks(day_of_week, title, start_time, end_time)
-- VALUES('Friday', 'Work', '08:30:00', '05:00:00');
-- INSERT INTO time_blocks(day_of_week, title, start_time, end_time)
-- VALUES('Saturday', 'Work', '10:45:00', '07:15:00')
SELECT *
FROM time_blocks;