-- TO TEST IF VIOLATING CONTRAINTS WORKS. YEARLY SALARY IS TARGET BY THE YEARLYSALARYPOSITIVE CONTRAINT WHICH STOPS IT FROM BEING LESS THAN 0 WHCH IS WHY EVEN THOUGH IT ISN'T "MENTIONED" HERE IT'S STILL TAKING AFFECT. TREAT THE CONSTRAINT AS THE SAME NAME IN THIS CASE
INSERT INTO users(full_name, yearly_salary, current_status)
VALUES ('Some User', -1000, 'unemployed');